# Generated by Django 4.2.29 on 2026-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Glow by Riri', max_length=120)),
                ('slogan', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
