# Generated by Django 4.2.29 on 2026-03-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image (Cloudinary)"),
        ),
    ]
