# Generated by Django 4.2.29 on 2026-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_service_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('soins', 'Soins capillaires'), ('coiffure', 'Coiffure'), ('perruques', 'Perruques & Lace'), ('autres', 'Autres')], default='autres', max_length=50, verbose_name='Catégorie'),
        ),
    ]
