# Generated by Django 4.2.29 on 2026-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('coiffure', 'Coiffure'), ('perruques', 'Perruques & Lace'), ('autres', 'Autres')], default='autres', max_length=50, verbose_name='Catégorie'),
        ),
    ]
