# Generated by Django 4.2.29 on 2026-03-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name="URL de l'image (Cloudinary)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Photo du service',
                'verbose_name_plural': 'Photos du service',
                'ordering': ['order'],
            },
        ),
    ]
