# Generated by Django 4.2.29 on 2026-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('coiffure', 'Coiffure')], default='autres', max_length=50, verbose_name='Catégorie'),
        ),
    ]
