# Generated by Django 4.2.29 on 2026-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['price'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ex: 20 pour -20%. Laisser 0 si aucun rabais.', max_digits=5, verbose_name='Rabais (%)'),
        ),
    ]
