# Generated by Django 4.2.29 on 2026-03-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Rappel envoyé'),
        ),
    ]
