# Generated by Django 4.2.29 on 2026-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_add_reminder_sent_to_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text="Montant de l'acompte requis pour ce service.", max_digits=8, verbose_name='Acompte ($)'),
        ),
    ]
