# Generated by Django 4.2.29 on 2026-04-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_add_deposit_amount_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nattes_deja_faites',
            field=models.BooleanField(blank=True, help_text='True = cliente arrive avec ses nattes, False = nattes à faire sur place (+10 $ CAD), None = non applicable.', null=True, verbose_name='Nattes déjà faites'),
        ),
        migrations.AddField(
            model_name='service',
            name='nattes_requises',
            field=models.BooleanField(default=False, help_text="Cochez si ce service nécessite des nattes avant la pose. La cliente aura l'option d'indiquer si elle les a déjà (prix normal) ou non (+10 $ CAD).", verbose_name='Nattes requises'),
        ),
    ]
