# Generated by Django 4.2.29 on 2026-04-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_add_nattes_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='0 = en premier. Mettez 99 pour afficher ce service en dernier.', verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='service',
            name='sans_creneau',
            field=models.BooleanField(default=False, help_text='Cochez pour les services de type dépôt/retrait (customisation, coloration…). Les clientes feront une demande simple sans choisir de créneau.', verbose_name='Service sans créneau'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Message (optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, verbose_name='Cliente contactée')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Demande de service',
                'verbose_name_plural': 'Demandes de services',
                'ordering': ['-created_at'],
            },
        ),
    ]
