# Generated by Django 4.2.29 on 2026-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('produits', 'Nos produits'), ('perruques', 'Perruques'), ('lace', 'Lace')], default='produits', max_length=20, verbose_name='Catégorie'),
        ),
    ]
