# Generated by Django 4.2.29 on 2026-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage'),
    ]

    def migrate_lace_to_perruques(apps, _):
        Product = apps.get_model('shop', 'Product')
        Product.objects.filter(category='lace').update(category='perruques')

    operations = [
        migrations.RunPython(migrate_lace_to_perruques, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('produits', 'Nos produits'), ('perruques', 'Perruques & Lace')], default='produits', max_length=20, verbose_name='Catégorie'),
        ),
    ]
