# Generated by Django 4.2.29 on 2026-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_lace_into_perruques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['variant_type', 'price', 'label'], 'verbose_name': 'Variante', 'verbose_name_plural': 'Variantes'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='label',
            field=models.CharField(default='', help_text='Ex: 12 pouces, 13x4 HD, 180%', max_length=50, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('longueur', 'Longueur'), ('fermeture', 'Type de lace'), ('densite', 'Densité')], default='longueur', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix (longueur seulement)'),
        ),
    ]
