# Generated by Django 4.2.29 on 2026-03-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_variant_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la vidéo (Cloudinary)'),
        ),
    ]
