# Generated by Django 4.2.29 on 2026-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ex: 20 pour -20%. Laisser 0 si aucun rabais.', max_digits=5, verbose_name='Rabais (%)'),
        ),
    ]
