# Generated by Django 4.2.29 on 2026-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_add_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('perruque', 'Perruque'), ('lace', 'Lace / Frontale')], default='perruque', help_text="Perruque ou Lace/Frontale (pour l'ordre d'affichage)", max_length=20, verbose_name='Type'),
        ),
    ]
