# Generated by Django 4.2.29 on 2026-03-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('produit', 'Produit'), ('perruque', 'Perruque'), ('lace', 'Lace / Frontale')], default='produit', help_text="Détermine la catégorie du produit et son ordre d'affichage.", max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('longueur', 'Longueur'), ('densite', 'Densité')], default='longueur', max_length=20, verbose_name='Type'),
        ),
    ]
