# Generated by Django 4.2.29 on 2026-03-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cleanup_product_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='Expédiée'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Entre le numéro de suivi du transporteur', max_length=200, verbose_name='Numéro de suivi'),
        ),
    ]
