# Generated by Django 4.2.29 on 2026-03-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_add_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Décocher pour masquer ce produit du site.', verbose_name='Disponible'),
        ),
    ]
