# Generated by Django 4.2.29 on 2026-03-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_disponible_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('produits', 'Nos produits'), ('perruques', 'Perruques & Lace'), ('bundles', 'Bundles')], default='produits', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('produit', 'Produit'), ('perruque', 'Perruque'), ('lace', 'Lace / Frontale'), ('bundle', 'Bundle')], default='produit', help_text="Détermine la catégorie du produit et son ordre d'affichage.", max_length=20, verbose_name='Type'),
        ),
    ]
