# Generated by Django 4.2.29 on 2026-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_bundle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('produits', 'Nos produits'), ('perruques', 'Perruques'), ('bundles', 'Bundles & Laces')], default='produits', max_length=20, verbose_name='Catégorie'),
        ),
    ]
