# Generated by Django 4.2.29 on 2026-03-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_perruques_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('video_url', models.URLField(verbose_name='URL de la vidéo (Cloudinary)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL miniature (optionnel)')),
                ('badge', models.CharField(blank=True, help_text='Ex: NEW, 5.4K vues', max_length=50, verbose_name='Badge')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Produit lié')),
            ],
            options={
                'verbose_name': 'Vidéo tutoriel',
                'verbose_name_plural': 'Vidéos tutoriels',
                'ordering': ['order'],
            },
        ),
    ]
