# Generated by Django 4.2.29 on 2026-03-20 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_add_tutorial_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📹 Gérer les vidéos tutoriels',
                'verbose_name_plural': '📹 Gérer les vidéos tutoriels',
            },
        ),
        migrations.RemoveField(
            model_name='tutorialvideo',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='badge',
            field=models.CharField(blank=True, help_text='Ex: NEW, POPULAIRE', max_length=50, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.tutorialsection'),
        ),
    ]
