# Generated by Django 4.2.29 on 2026-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Numéro de suivi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('longueur', 'Longueur'), ('lace', 'Taille de lace'), ('densite', 'Densité'), ('couleur', 'Couleur')], default='longueur', max_length=20, verbose_name='Type'),
        ),
    ]
