# Generated by Django 4.2.29 on 2026-04-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_add_shipping_address_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('longueur', 'Longueur'), ('lace', 'Taille de lace'), ('type_lace', 'Type de lace'), ('densite', 'Densité'), ('couleur', 'Couleur')], default='longueur', max_length=20, verbose_name='Type'),
        ),
    ]
