# Generated by Django 4.2.29 on 2026-04-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_add_type_lace_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text="Photo qui s'affiche automatiquement quand cette option est sélectionnée", verbose_name='Photo (optionnel)'),
        ),
    ]
