# Generated by Django 4.2.29 on 2026-04-04

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        base_slug = slugify(product.name)
        if not base_slug:
            base_slug = f"product-{product.id}"
        slug = base_slug
        counter = 1
        while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        product.slug = slug
        product.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_add_photo_url_to_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Réduction (%)')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='Utilisations max')),
                ('uses_count', models.IntegerField(default=0, verbose_name='Utilisations')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
            },
        ),
        # Add slug as non-unique first so we can populate it
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, default=''),
            preserve_default=False,
        ),
        # Data migration: generate slugs
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Now make it unique
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide pour stock illimité.', null=True, verbose_name='Stock'),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('session_key', 'product')},
            },
        ),
    ]
