# Generated by Django 4.2.29 on 2026-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_set_installation_for_perruques'),
    ]

    operations = [
        migrations.AddField(
            model_name='lacevariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité. 0 = rupture de stock.', null=True, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité. 0 = rupture de stock.', null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='lacevariant',
            name='longueur',
            field=models.CharField(help_text='Ex: 10 pouces', max_length=20, verbose_name='Longueur'),
        ),
    ]
